### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by a-figerou** [MrLostInTheInternet/FAM#1]
**Presentation**

Is it a project open to contribution ? 

Your project has interested me a lot thanks to my mountain passion. I am living in Grenoble, Alpes. The idea of helping people with information regarding injurings is giving me happyness.

I am person with great creativity and ideas, that has programming skills.

Thanks in advance

**Comment by MrLostInTheInternet** [comment]
Hi, at the moment, it is a project for a bachelor's thesis. It will be completed before 17th October, until then I'm glad you're interested, and feel free to write to me what innovative ideas you would like to see in the application.

After 17th October, I'll talk to my collegue that developed this idea of the App and We will decide to open or not the contributions. Let me know what do you think about it.

I thank you in advance too
